minimumReleaseAge: 10080

minimumReleaseAgeExclude:
  - '@giltayar/*'
  - '@typescript/*'
  - '@types/*'
  - eslint*
  - '@eslint/*'

neverBuiltDependencies:
  - es5-ext

overrides:
  '@giltayar/carmel-tools-cardcom-integration': link:../../carmel-tools/cardcom-integration
