minimumReleaseAge: 10080

minimumReleaseAgeExclude:
  - '@giltayar/*'
  - '@typescript/*'
  - '@types/*'
  - eslint*
  - '@eslint/*'

patchedDependencies:
  fastify-type-provider-zod@5.1.0: patches/fastify-type-provider-zod@5.1.0.patch
