allowBuilds:
  '@railway/cli': true
  '@firebase/util': false
  '@swc/core': false
  protobufjs: false
  es5-ext: false

minimumReleaseAgeExclude:
  - '@giltayar/carmel-tools-smoove-integration@5.3.0'

updateConfig:
  ignoreDependencies:
    - postgres
