allowBuilds:
  '@railway/cli': true
  '@firebase/util': false
  '@swc/core': false
  protobufjs: false
  es5-ext: false

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@giltayar/*'

updateConfig:
  ignoreDependencies:
    - postgres
