apiVersion: v1
kind: Service
metadata:
  name: {{name}}
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: main
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: {{name}}
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
