CREATE TABLE
  sale_data_delivery (
    data_id UUID, -- either this (for manual sales)...
    data_cardcom_id UUID, -- or that (for sales generated by cardcom)
    city TEXT NOT NULL,
    street TEXT NOT NULL,
    street_number TEXT NOT NULL,
    entrance TEXT NOT NULL,
    floor TEXT NOT NULL,
    apartment_number TEXT NOT NULL,
    contact_phone TEXT NOT NULL,
    notes_to_delivery_person TEXT NOT NULL
  );

CREATE UNIQUE INDEX sale_data_delivery_idx ON sale_data_delivery (data_id, data_cardcom_id);
